import Icons from "../../assets/icons/indexIcons";

const hardSkillsArray = [
  {
    title: "HTML",
    icon: Icons.iconHtml5,
    content: "Maîtrise des balises et de la structure des pages web.",
    link: "#",
    fileName: "#",
    grade: "Avancé",
    category: "frontend",
  },
  {
    title: "CSS",
    icon: Icons.iconCss3,
    content: "Styles, mises en page, animations et responsivité.",
    link: "#",
    fileName: "#",
    grade: "Avancé",
    category: "frontend",
  },
  {
    title: "SASS",
    icon: Icons.iconSass,
    content: "Utilisation de Sass pour un CSS plus maintenable et évolutif.",
    link: "#",
    fileName: "#",
    grade: "Avancé",
    category: "frontend",
  },
  {
    title: "BULMA",
    icon: Icons.iconBulma,
    content:
      "Utilisation du framework CSS Bulma pour un rendu propre et rapide.",
    link: "#",
    fileName: "#",
    grade: "Intermédiaire",
    category: "frontend",
  },
  {
    title: "Javascript",
    icon: Icons.iconJs,
    content: "Manipulation du DOM, programmation orientée objet...",
    link: "#",
    fileName: "#",
    grade: "Avancé",
    category: "frontend",
  },
  {
    title: "GreenSock",
    icon: Icons.iconGreenSock,
    content: "Pour des animations stylées",
    link: "#",
    fileName: "#",
    grade: "Intermédiaire",
    category: "frontend",
  },
  {
    title: "TypeScript",
    icon: Icons.iconTypeScript,
    content:
      "Expérience dans l'utilisation de TypeScript pour un développement JavaScript plus robuste. Intégration réussie avec des frameworks comme React.",
    link: "#",
    fileName: "#",
    grade: "Intermédiaire",
    category: "tooling",
  },
  {
    title: "React",
    icon: Icons.iconReact,
    content: "Développement d'interfaces utilisateur dynamiques et réactives.",
    link: "#",
    fileName: "#",
    grade: "Intermédiaire",
    category: "frontend",
  },
  {
    title: "NodeJS",
    icon: Icons.iconNode,
    content: "Création de serveurs côté backend avec Node.js.",
    link: "#",
    fileName: "#",
    grade: "Débutant",
    category: "backend",
  },
  {
    title: "MongoDB",
    icon: Icons.iconMongoDB,
    content: "Bases de données NoSQL avec MongoDB.",
    link: "#",
    fileName: "#",
    grade: "Débutant",
    category: "backend",
  },
  {
    title: "ExpressJS",
    icon: Icons.iconExpressJs,
    content: "Construction d'applications web avec le framework Express.js.",
    link: "#",
    fileName: "#",
    grade: "Débutant",
    category: "backend",
  },
  {
    title: "PHP",
    icon: Icons.iconPHP,
    content:
      "Connaissance de base en PHP pour la gestion des formulaires et l'interaction avec les bases de données côté serveur. Capacité à implémenter des fonctionnalités côté serveur dans les applications web.",
    link: "#",
    fileName: "#",
    grade: "Débutant",
    category: "backend",
  },
  {
    title: "SQL",
    icon: Icons.iconSQL,
    content:
      "Compétences débutantes en SQL pour la gestion des bases de données relationnelles. Capacité à exécuter des requêtes SQL pour interagir avec les données et effectuer des opérations CRUD (Création, Lecture, Mise à jour, Suppression).",
    link: "#",
    fileName: "#",
    grade: "Débutant",
    category: "backend",
  },
  {
    title: "Github",
    icon: Icons.iconGithub,
    content:
      "Gestion de versions, collaboration et partage de code à travers la plate-forme GitHub. Profil GitHub disponible avec des projets publics et contributions open source.",
    link: "#",
    fileName: "",
    grade: "Avancé",
    category: "tooling",
  },
  {
    title: "Figma",
    icon: Icons.iconFigma,
    content:
      "Utilisation de Figma pour la conception d'interfaces utilisateur (UI) et la collaboration dans le processus de développement. Création de maquettes et prototypes interactifs.",
    link: "#",
    fileName: "#",
    grade: "Intermédiaire",
    category: "tooling",
  },
];

export default hardSkillsArray;
